name: Debug CI Environment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  debug:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            safe_base: /home/runner/work/mcp-forensic-toolkit/mcp-forensic-toolkit
          - os: macos-latest
            safe_base: /Users/runner/work/mcp-forensic-toolkit/mcp-forensic-toolkit
          - os: windows-latest
            safe_base: C:\Users\runner\work\mcp-forensic-toolkit\mcp-forensic-toolkit

    env:
      SAFE_BASE: ${{ matrix.safe_base }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print OS info
        run: |
          echo "Running on OS: $RUNNER_OS"
          python --version
        shell: bash

      - name: List root directory files (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Listing root files (Windows)"
          dir
        shell: pwsh

      - name: List root directory files (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Listing root files (Linux/macOS)"
          ls -al
        shell: bash

      - name: List SAFE_BASE contents (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Listing SAFE_BASE path: $env:SAFE_BASE"
          dir $env:SAFE_BASE
        shell: pwsh

      - name: List SAFE_BASE contents (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Listing SAFE_BASE path: $SAFE_BASE"
          ls -al "$SAFE_BASE"
        shell: bash

      - name: Show environment variables (Windows)
        if: runner.os == 'Windows'
        run: |
          Get-ChildItem Env:
        shell: pwsh

      - name: Show environment variables (Linux/macOS)
        if: runner.os != 'Windows'
        run: env
        shell: bash