name: Python CI with Poetry

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            safe_base: /home/runner/work/mcp-forensic-toolkit/mcp-forensic-toolkit
          - os: macos-latest
            safe_base: /Users/runner/work/mcp-forensic-toolkit/mcp-forensic-toolkit
          - os: windows-latest
            safe_base: D:\a\mcp-forensic-toolkit\mcp-forensic-toolkit

    env:
      SAFE_BASE: ${{ matrix.safe_base }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print OS info
        run: |
          echo "Running on OS: $RUNNER_OS"
          python --version
        shell: bash

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
        shell: bash

      - name: Configure Poetry to not create virtualenv
        run: poetry config virtualenvs.create false
        shell: bash

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
        shell: bash

      - name: Run tests with pytest
        run: pytest -v
        shell: bash

      # For Windows, use PowerShell explicitly on Windows runs
      - name: Windows-specific commands
        if: runner.os == 'Windows'
        run: |
          echo "Running Windows-specific setup if needed"
        shell: pwsh